/**
 * The `ResponseLogin` class represents the response after a login attempt.
 * It stores a token generated by the server that can be used to authenticate future requests.
 */
export class ResponseLogin {
  public tokenGenBack: string;

  /**
   * Creates an instance of the `ResponseLogin` class.
   *
   * @param tok - The token generated by the server after a successful login attempt.
   */
  
  constructor(tok: string) {
    this.tokenGenBack = tok;
  }
}
